### ISSUE TITLE
Home's background image is not the same width as the navbar

### ISSUE THREAD

**Issue by jamesgott1** [jjessel/lol-stats#2]
On the Home tab, the navbar is a 100% width of however wide the browser window is. However when you scroll to the right, you will see that the background image is not the same width and will exceed the width of the window and the width of the navbar. See image below:

![Screen Shot 2020-08-13 at 12 53 56 PM](https://user-images.githubusercontent.com/53617669/90163618-5625b000-dd64-11ea-886a-1f39fccf483b.png)

**Comment by jjessel** [comment]
Updated the image sizing. The header will be wider if you reach max image size. Looks better now though. Not final design.
